<?php
/*
 *   Crafted On Wed Oct 16 2024
 *   From his finger tips, through his IDE to your deployment environment at full throttle with no bugs, loss of data,
 *   fluctuations, signal interference, or doubt—it can only be
 *   the legendary coding wizard, Martin Mbithi (martin.mbithi@makueni.go.ke, www.martmbithi.github.io)
 * 
 *   www.makueni.go.ke
 *   info@makueni.go.ke
 *
 *
 *   The Government Of Makueni DevSecOps Band User License Agreement
 *   Copyright (c) 2023 Government of Makueni County
 *
 *
 *   1. LICENSE TO RULE
 *   Welcome to the elite club! Crafted by the ingenious Martin Mbithi, this software comes with the all-powerful,
 *   revocable, personal, non-exclusive, and non-transferable right to install and activate this masterpiece on ONE  
 *   lucky computer for your official, non-commercial escapades. Got a commercial itch? Better get that license first. 
 *   No peeking, sharing, or showing off this software to anyone else—strictly against the rules!
 *
 *   2. COPYRIGHT POWER
 *   This software, a creation of Martin Mbithi under the banner of the Government Of Makueni DevSecOps Band, is guarded by 
 *   copyright law and international treaties. So, don’t even think about messing with the proprietary notices, labels, 
 *   or marks—what’s his stays his!
 *
 *
 *   3. USE IT RIGHT OR LOSE IT
 *   You may not, and you may not let your fellow geeks:
 *   (a) hack, reverse engineer, decompile, decode, decrypt, disassemble, or attempt any sorcery to reveal the source code;
 *   (b) modify, remix, distribute, or create spinoffs of this masterpiece;
 *   (c) make copies (aside from your trusty backup), distribute, show off in public, transmit, sell, rent, lease, or otherwise
 *   exploit this software like it’s yours. Spoiler: it’s not!
 *
 *
 *   4. GAME OVER, MAN!
 *   This license is your golden ticket until one of us says otherwise. Want to end it? Smash the software and all its copies into
 *   digital dust. Break any rules? The license self-destructs, and you’ll need to nuke all copies—no second chances!
 *
 *
 *   5. NO PIXEL-PERFECT PROMISES
 *   Martin Mbithi and the Government Of Makueni DevSecOps Band don’t guarantee this software is glitch-free—think of it as a feature
 *   not a bug! We disclaim all other warranties, whether expressed or implied, including, but not limited to, implied warranties of merchantability
 *   fitness for a particular purpose, and non-infringement of third-party rights. Some jurisdictions have their own funky rules, so your mileage may
 *   vary. But remember: use at your own risk, brave user!
 *
 *
 *   6. KEEP THE PARTY GOING
 *   If a court zaps any part of this license, no worries—the rest of it keeps the party alive. One piece fails, but the agreement stands strong!
 *
 *
 *   7. NO DRAMA, NO DAMAGES
 *   Under no circumstances shall Martin Mbithi, the Government Of Makueni DevSecOps Band, or their minions be held responsible for any wild, indirect
 *   or accidental chaos from using this software—even if we warned you! And if you think you’ve got a claim, the most you’re getting is what you paid for the 
 *   license—if anything. Keep calm and code on!
 *
 */
require_once('../vendor/autoload.php');

use Dompdf\Dompdf;

$dompdf = new Dompdf();

$html = '
<!DOCTYPE html>
<html>
    <head>
        <meta name="" content="XYZ,0,0,1" />
        <style type="text/css">
            table {
                font-size: 12px;
                padding: 4px;
                border-collapse: collapse; /* Ensure borders are merged */
                width: 100%;
            }

            th {
                text-align: left;
                padding: 4pt;
                background-color: #f2f2f2; /* Header background color */
            }

            td {
                padding: 5pt;
            }

            .footer {
                width: 100%;
                text-align: center;
                position: fixed;
                bottom: 5px;
            }

            .list_header {
                font-family: "Times New Roman", Times, serif;
                text-align: center;
                margin-bottom: 20px;
            }

            /* Additional styles */
            #total_row {
                font-weight: bold;
                background-color: #e2e2e2; /* Total row background */
            }
        </style>
    </head>

    <body style="margin:1px;">
        <div class="footer">
            <hr>
            <i>This document has been generated by ' . $user_names . ' On ' . date('d M Y g:ia') . '</i>
        </div>
        <div class="list_header">
            <h3>
                <img src="' . $base64 . '" style="width:65%" alt="Logo"> <br>
                <hr style="width:100%" color=black> <br>
                ' . $subcounty . ' Subcounty Enrollments Breakdown Per Ward<br>
            </h3>                        
        </div>
        <table border="1" cellspacing="0" style="font-size:9pt">
            <thead>
                <tr>
                    <th style="width:10%">S/N</th>
                    <th style="width:100%">Ward</th>
                    <th style="width:100%">ECDE Centers</th>
                    <th style="width:100%">Pupils in Playgroup</th>
                    <th style="width:100%">Pupils in PP1</th>
                    <th style="width:100%">Pupils in PP2</th>
                    <th style="width:100%">Total</th>
                </tr>
            </thead>
            <tbody>';
                $pdf_sql = mysqli_query($mysqli, "SELECT * FROM ward WHERE ward_sub_couty_id = '{$id}'");
                $cnt = 1;
                $total_centers = 0;
                $total_baby_class = 0;
                $total_pp1 = 0;
                $total_pp2 = 0;
                $total_trainees = 0;

                if (mysqli_num_rows($pdf_sql) > 0) {
                    while ($row = mysqli_fetch_array($pdf_sql)) {

                        // Get counts for each category
                        $query = "SELECT COUNT(*) FROM ecde_centers WHERE center_ward_id = '{$row['ward_id']}'";
                        $stmt = $mysqli->prepare($query);
                        $stmt->execute();
                        $stmt->bind_result($number_of_centers);
                        $stmt->fetch();
                        $stmt->close();

                        $query = "SELECT COUNT(*) FROM pupils p 
                                INNER JOIN ecde_centers c ON c.center_id = p.pupil_center_id 
                                WHERE c.center_ward_id = '{$row['ward_id']}' AND p.pupil_academic_level = 'Playgroup'";
                        $stmt = $mysqli->prepare($query);
                        $stmt->execute();
                        $stmt->bind_result($baby_class);
                        $stmt->fetch();
                        $stmt->close();

                        $query = "SELECT COUNT(*) FROM pupils p 
                                INNER JOIN ecde_centers c ON c.center_id = p.pupil_center_id 
                                WHERE c.center_ward_id = '{$row['ward_id']}' AND p.pupil_academic_level = 'PP1'";
                        $stmt = $mysqli->prepare($query);
                        $stmt->execute();
                        $stmt->bind_result($pp1);
                        $stmt->fetch();
                        $stmt->close();

                        $query = "SELECT COUNT(*) FROM pupils p 
                                INNER JOIN ecde_centers c ON c.center_id = p.pupil_center_id 
                                WHERE c.center_ward_id = '{$row['ward_id']}' AND p.pupil_academic_level = 'PP2'";
                        $stmt = $mysqli->prepare($query);
                        $stmt->execute();
                        $stmt->bind_result($pp2);
                        $stmt->fetch();
                        $stmt->close();

                        $query = "SELECT COUNT(*) FROM pupils p 
                                INNER JOIN ecde_centers c ON c.center_id = p.pupil_center_id 
                                WHERE c.center_ward_id = '{$row['ward_id']}'";
                        $stmt = $mysqli->prepare($query);
                        $stmt->execute();
                        $stmt->bind_result($total_trainees_ward);
                        $stmt->fetch();
                        $stmt->close();

                        // Update totals
                        $total_centers += $number_of_centers;
                        $total_baby_class += $baby_class;
                        $total_pp1 += $pp1;
                        $total_pp2 += $pp2;
                        $total_trainees += $total_trainees_ward;

                        // Append row to HTML
                        $html .= '
                        <tr>
                            <td>' . $cnt . '</td>
                            <td>' . $row['ward_name'] . '</td>
                            <td>' . number_format($number_of_centers) . '</td>
                            <td>' . number_format($baby_class) . '</td>
                            <td>' . number_format($pp1) . '</td>
                            <td>' . number_format($pp2) . '</td>
                            <td>' . number_format($total_trainees_ward) . '</td>
                        </tr>';
                        
                        $cnt++;
                    }
                }

                // Add total row
                $html .= '
                    <tr id="total_row">
                        <td colspan="2">Total</td>
                        <td>' . number_format($total_centers) . '</td>
                        <td>' . number_format($total_baby_class) . '</td>
                        <td>' . number_format($total_pp1) . '</td>
                        <td>' . number_format($total_pp2) . '</td>
                        <td>' . number_format($total_trainees) . '</td>
                    </tr>';

                $html .= '
            </tbody>
        </table>
    </body>
</html>
';

// Generate PDF
$dompdf->load_html($html);
$dompdf->set_paper('A4', 'landscape');
$dompdf->set_option('isHtml5ParserEnabled', true);
$dompdf->render();
$dompdf->stream($subcounty . ' Subcounty Enrollments Breakdown Per Ward', array("Attachment" => 1));

$options = $dompdf->getOptions();
$options->setDefaultFont('');
$dompdf->setOptions($options);
